#!/bin/python3

import random
import string
import argparse

def shuffle_string(s: str):
     char_list = list(s)
     random.shuffle(char_list)
     return ''.join(char_list)

def password_generator(
    length: int, 
    include_special_characters: bool = False
):
    password = ""
    different_types = 3

    if include_special_characters:
            different_types = 4

    numbers = random.randint(1, length - different_types)
    for _ in range(numbers):
        password += random.choice(string.digits)
    # print(numbers)
    
    lowercase_letters = random.randint(1, length - len(password) - 1)
    for _ in range(lowercase_letters):
        password += random.choice(string.ascii_lowercase)
    # print(lowercase_letters)

    uppercase_letters = 1
    if (length - len(password) != 1):
        uppercase_letters = random.randint(1, length - len(password) - 1) if include_special_characters else length - len(password)
    for _ in range(uppercase_letters):
        password += random.choice(string.ascii_uppercase)
    # print(uppercase_letters)

    if include_special_characters:
        special_characters = length - len(password)
        for _ in range(special_characters):
            password += random.choice(string.punctuation)
        # print(special_characters)

    # print(f"total without special chars: {numbers + lowercase_letters + uppercase_letters}")
    # print(f"password length: {len(password)}")
    # print(f"password: {password}")

    return shuffle_string(password)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate a random password.")
    parser.add_argument("length", type=int, help="Length of the password")
    parser.add_argument("-s", "--special", action="store_true", help="Include special characters in the password")
    
    args = parser.parse_args()
    
    print(password_generator(args.length, args.special))
